server:
  port: 8888

security:
  ignored: /**

sts:
  resourceServers:
  - audience: "sts"
    jwksUrl: "http://localhost:8888/pop"
  - audience: "sts-service-component-example"
    jwksUrl: "http://localhost:8887/pop"
  - audience: "sts-service-component"
    jwksUrl: "http://sts-service-component:8887/service-component/pop"
  keymanagement:
    rotation:
      checkInterval: 60000
      encKeyPairs:
        minKeys: 5
        enabled: true
      signKeyPairs:
        minKeys: 5
        enabled: true
      secretKeys:
        minKeys: 5
        enabled: true
    persistence:
      containerName: adsts-container
      password: ahDa5cahda1ooxahh8aikaeChiePaeKa
    keystore:
      password: LuYie2eebebahNgoopiehaiV9wis7anu
      type: UBER
      name: adsts-keystore
      alias_prefix: adsts-
      keys:
        encKeyPairs:
          initialCount: 5
          algo: RSA
          sigAlgo: SHA256withRSA
          size: 2048
          name: Adorsys Security Token Service
          validityInterval: 3600000
          legacyInterval: 86400000
        signKeyPairs:
          initialCount: 5
          algo: RSA
          sigAlgo: SHA256withRSA
          size: 2048
          name: Adorsys Security Token Service
          validityInterval: 3600000
          legacyInterval: 86400000
        secretKeys:
          initialCount: 5
          algo: AES
          size: 256
          validityInterval: 3600000
          legacyInterval: 86400000
