liquibase:
  default-schema: sts

flyway:
  locations:
  - db/migration/mysql

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sts
  jpa:
    properties:
      hibernate:
        show-sql: true
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
