server:
  port: 8888

security:
  ignored: /**

app:
  servers:
  - audience: "my_audience"
    jwksUrl: "http://localhost:8080/pop"
  - audience: "my_audience_2"
    jwksUrl: "http://localhost:8080/pop"
