server:
  port: 8888

security:
  ignored: /**

logging:
  level.de.adorsys.sts.keymanagement.KeyRotationSchedule: 'info'

sts:
  resourceServers:
  - audience: "sts"
    jwksUrl: "http://localhost:8888/pop"
  - audience: "my_audience"
    jwksUrl: "http://localhost:8888/pop"
  - audience: "my_audience_2"
    jwksUrl: "http://another_server:8080/pop"
  - audience: "sts-service-component-example"
    jwksUrl: "http://localhost:8887/pop"
  - audience: "sts-service-component"
    jwksUrl: "http://sts-service-component:8887/service-component/pop"
  keymanagement:
    persistence:
      containerName: adsts-container
      password: 0123456789ABCDEF
    keystore:
      password: FEDCBA9876543210
      type: UBER
      name: adsts-keystore
      alias_prefix: adsts-
      rotationCheckInterval: 60000
      keys:
        encKeyPairs:
          rotation:
            validityInterval: 432000000
            legacyInterval: 86400000
            minKeys: 5
            enabled: true
          initialCount: 5
          algo: RSA
          sigAlgo: SHA256withRSA
          size: 2048
          name: Adorsys Security Token Service
        signKeyPairs:
          rotation:
            validityInterval: 432000000
            legacyInterval: 86400000
            minKeys: 5
            enabled: true
          initialCount: 5
          algo: RSA
          sigAlgo: SHA256withRSA
          size: 2048
          name: Adorsys Security Token Service
        secretKeys:
          rotation:
            validityInterval: 432000000
            legacyInterval: 86400000
            minKeys: 5
            enabled: false
          initialCount: 5
          algo: AES
          size: 256
