server:
  port: 8888

security:
  ignored: /**

logging:
  level.de.adorsys.sts.keyrotation.KeyRotationSchedule: 'debug'

sts:
  resourceServers:
  - audience: "sts"
    jwksUrl: "http://localhost:8888/pop"
  - audience: "my_audience"
    jwksUrl: "http://localhost:8888/pop"
  - audience: "my_audience_2"
    jwksUrl: "http://another_server:8080/pop"
  - audience: "sts-service-component-example"
    jwksUrl: "http://localhost:8887/pop"
  - audience: "sts-service-component"
    jwksUrl: "http://sts-service-component:8887/service-component/pop"
  keymanagement:
    rotation:
      checkInterval: 5000
      encKeyPairs:
        minKeys: 5
        enabled: true
      signKeyPairs:
        minKeys: 5
        enabled: true
      secretKeys:
        minKeys: 5
        enabled: true
    persistence:
      containerName: adsts-container
      password: 0123456789ABCDEF
    keystore:
      password: FEDCBA9876543210
      type: UBER
      name: adsts-keystore
      alias_prefix: adsts-
      keys:
        encKeyPairs:
          initialCount: 5
          algo: RSA
          sigAlgo: SHA256withRSA
          size: 2048
          name: Adorsys Security Token Service
          validityInterval: 30000
          legacyInterval: 20000
        signKeyPairs:
          initialCount: 5
          algo: RSA
          sigAlgo: SHA256withRSA
          size: 2048
          name: Adorsys Security Token Service
          validityInterval: 30000
          legacyInterval: 20000
        secretKeys:
          initialCount: 5
          algo: AES
          size: 256
          validityInterval: 30000
          legacyInterval: 20000
