language: java

jdk:
  - oraclejdk8

services:
  - docker

install:
  - mvn --settings .travis/settings.xml install -DskipTests -Dmaven.javadoc.skip=true -B -V

script:
  - mvn --settings .travis/settings.xml package -DskipTests -B -V

before_deploy:
  - echo $GPG_SECRET_KEY | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

deploy:
  -
    skip_cleanup: true
    provider: script
    script: /bin/bash .travis/deploy.sh
    on:
      tags: true
      # matches: vX.Y.Z, vX.Y.Z-A, vX.Y.Z-A-B.C.D, vX.Y.Z-A-B.C.D-E
      condition: "$TRAVIS_TAG =~ ^v([[:digit:]]+\\.)+[[:digit:]]+(-[[:digit:]]+)?(-([[:digit:]]+\\.)+[[:digit:]]+(-[[:digit:]]+)?)?$"

env:
  global:
  - STS_EXAMPLE_DOCKER_IMAGE_NAME=adorsys/sts-example
  # encrypted docker hub credentials
  - secure: sZxiKpqHwFAeyTBHdIbZ55lVT2c5cl1EEvpJRtMYig3oZZB5GuN+BW/jnqtmZYtoJHPYcVWkOmlZk3ido0NQOzOVmvbHvv7GLBUfszNYji6Xjba14y+pwVODqQvwqGHg7kLFWFoYqc1ru2rWWCZJNwAZUbxaghw1BGYFti6Dbx0M6wwZpRO2qpbVLiFZ955/vhnKV/fPXkvAGW+2CcO8KGo+IQdqFVkXzPnzinE7dWJ44Yk4edZKvfwzQAm56taMKxvW0JewBHQZm661ng7g26cjJEJ0fTw1oamPI2B5UzdtYc9i62nBv1qfEkZQNLjVPuvlSBwXcahiX8556GKAeLsUr1GjpkGOzh3X2j4W/XPi9MK7OePsXK0UxR2H3CI9+ANS85WxUaVj8ZSgqVRV+zHpNhOhy9krs+qPaeRi2/mvDzy0TI/dL7GJfzDEcuHCyZHFlYmB76fdwHWMMO7NO1CFjqQrNcFiYBzent7lcfKGFnuLGDYDrzFkQapaKBSA3Em3/IM0gMszrjA7YUBQ9EYYK1QQin60C3F9cZSwiKHs8gPCbxYr7GSrKJmkhsa6SfIK+A31Ede42z0UVvYIUKoDwFUaiiXNe5B+vO+sEPfFcvxmfRGC1Xc5zpOtfioBhT/Azd4rcPA9PWeYGORh1a4ikqzO08CaN9rTMtIqzzA=
