language: java

jdk:
  - oraclejdk8

install:
  - mvn --settings .travis/settings.xml install -DskipTests -Dmaven.javadoc.skip=true -B -V

script:
  - mvn --settings .travis/settings.xml package -DskipTests -B -V

deploy:
  -
    skip_cleanup: true
    provider: script
    script: /bin/bash .travis/deploy.sh
    on:
      tags: true
