language: java

jdk:
  - oraclejdk8

services:
  - docker

install:
  - mvn --settings .travis/settings.xml clean install -DskipTests -Dmaven.javadoc.skip=true -B -V

script:
  - mvn --settings .travis/settings.xml clean package -DskipTests -B -V

before_deploy:
  - echo $GPG_SECRET_KEY | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

deploy:
  -
    skip_cleanup: true
    provider: script
    script: /bin/bash .travis/deploy.sh
    on:
      tags: true
      # matches: vX.Y.Z, vX.Y.Z-A, vX.Y.Z-A-B.C.D, vX.Y.Z-A-B.C.D-E
      condition: "$TRAVIS_TAG =~ ^v([[:digit:]]+\\.)+[[:digit:]]+(-[[:digit:]]+)?(-([[:digit:]]+\\.)+[[:digit:]]+(-[[:digit:]]+)?)?$"

env:
  global:
  - STS_EXAMPLE_DOCKER_IMAGE_NAME=adorsys/sts-example
  # encrypted docker hub credentials
  - secure: alfKkoBx6kRFB5IzRhJ/wUE4NM9xs2LGGCVVXtwXavOTIWJAVZAZiZMPc4by25F9oWIisq6Sb3Htn85TFqiANUl9EzfyLcxOWD2VhcVLl/AhA6bkuFneBNKggNvmCwdMBdl+uil7FPp6TBAVbDvSSiOq3BV1SxmW3sO/Z+39PWNrfExfGDQGSpZ1LxbzRTFjZpJ5mxNhEC+qgYOpUaRzsNYq9X/TsmVfcUndmp+WoG4By/ALJC5mGCbET4xr5L0276V/5edzR1j+EcNbs6+zBEfkAlot6b/8xQHzWk7vSRlGOIn1Y1IudM+hSsRUwebvDraEEqX3iN8TXNOf8WEXc6ZhtjuXDs4kSGp8jeKK2Uf+bJGg4I3z+atpOBySJ/nF+lTCmDOpaXWKXzqXHXqnQ77aMQ03JApQnFsj0ct2qSY/LxtkEeVgXZqvm94tK3zMs+avdAkhbdTLDUuKhA5dMMfevJsAbiyXGZYuWRGUhhNEr5bVlPDZSPbI3U/g8PZm4f/CvxPFxlARWVOkgrPjpS9Xh7LMA8mSi7IXsEB2mXPAcRPenwMp4vg2RNKrPDPY/IJBbu4jBcL1FvCWaRL+02KWkwlGPKiqeo6isJNJa9YYUYRUzH38NUP69P2F2oMtyU2q2FcjrWkBmeeK+p5XETqPtfTrVgCrlrEtg5Q8t/A=
