logging:
  level.de.adorsys.sts.keyrotation.KeyRotationSchedule: 'debug'

flyway:
  locations:
  - db/migration/h2

spring:
  datasource:
    url: jdbc:h2:./sts_h2_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
