logging:
  level.de.adorsys.sts.keyrotation.KeyRotationSchedule: 'debug'

flyway:
  locations:
  - db/migration/postgres

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sts
  jpa:
    hibernate:
      show-sql: true
