server:
  port: 8887

spring:
  datasource:
    url: jdbc:postgresql://sts-db:5432/sts
    username: db_user
    password: db_user@123
  jpa:
    hibernate:
      show-sql: false

sts:
  audience_name: sts-service-component-example
  secret_claim_property_key: secretClaim
  authservers:
  - name: keycloak-playground
    issUrl: https://sso-keycloak-playground.dev.adorsys.de/auth/realms/moped
    jwksUrl: https://sso-keycloak-playground.dev.adorsys.de/auth/realms/moped/protocol/openid-connect/certs
    refreshIntervalSeconds: 600
  persistence:
    lockExpiry: 30000
  keymanagement:
    rotation:
      checkInterval: 60000
      encKeyPairs:
        minKeys: 5
        enabled: true
      signKeyPairs:
        minKeys: 5
        enabled: true
      secretKeys:
        minKeys: 5
        enabled: true
    persistence:
      containerName: adsts-container
      password: 0123456789ABCDEF
    keystore:
      password: FEDCBA9876543210
      type: UBER
      name: service-component-example-keystore
      alias_prefix: service-component-example-
      keys:
        encKeyPairs:
          initialCount: 5
          algo: RSA
          sigAlgo: SHA256withRSA
          size: 2048
          name: Adorsys Security Token Service
          validityInterval: 432000000
          legacyInterval: 86400000
        signKeyPairs:
          initialCount: 5
          algo: RSA
          sigAlgo: SHA256withRSA
          size: 2048
          name: Adorsys Security Token Service
          validityInterval: 432000000
          legacyInterval: 86400000
        secretKeys:
          initialCount: 5
          algo: AES
          size: 256
          validityInterval: 432000000
          legacyInterval: 86400000
