liquibase:
  default-schema: public

flyway:
  locations:
  - db/migration/flyway/postgres

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sts
  jpa:
    properties:
      hibernate:
        show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
