logging:
    level:
        org.springframework.web: DEBUG
        de.adorsys.sts.keyrotation.KeyRotationSchedule: DEBUG

sts:
  keymanagement:
    rotation:
      checkInterval: 60000
      encKeyPairs:
        minKeys: 5
        enabled: true
      signKeyPairs:
        minKeys: 5
        enabled: true
      secretKeys:
        minKeys: 5
        enabled: false
    persistence:
      containerName: adsts-container
      password: 0123456789ABCDEF
    keystore:
      password: FEDCBA9876543210
      type: UBER
      name: adsts-keystore
      alias_prefix: adsts-
      keys:
        encKeyPairs:
          initialCount: 5
          algo: RSA
          sigAlgo: SHA256withRSA
          size: 2048
          name: Adorsys Security Token Service
          validityInterval: 300000
          legacyInterval: 600000
        signKeyPairs:
          initialCount: 5
          algo: RSA
          sigAlgo: SHA256withRSA
          size: 2048
          name: Adorsys Security Token Service
          validityInterval: 300000
          legacyInterval: 600000
        secretKeys:
          initialCount: 5
          algo: AES
          size: 256
          validityInterval: 300000
          legacyInterval: 600000
